name = "lean4-natural-number-game"
version = "0.1.0"
defaultTargets = ["Lean4NaturalNumberGame"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0-rc2"

[[lean_lib]]
name = "Lean4NaturalNumberGame"
